name: VotingSample
services:
- name: vote
  project: vote/vote.csproj
- name: worker
  repository: https://github.com/drakon660/TyeMultiRepoWorker
- name: redis
  image: redis
  bindings:
    - port: 6378
      containerPort: 6379
      connectionString: ${host}:${port}
